name: Founded
favicon: null
layout_spectrum: 0
typography_spectrum: 0.8979764
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0
  lightness: 0.239151
  saturation: 0.2558247
  rhythmicContrast: 0.01036679
purpose: []
