layout_spectrum: 0
typography_spectrum: 0.3867294
color:
  saturation: 0.2558247
  brandStrength: 0.7984823
  lightness: 0.239151
  rhythmicContrast: 0.01036679
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
name: Founded
