name: Founded
favicon: null
layout_spectrum: 0.49973
typography_spectrum: 0.37774
title: Founded
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#2b2b2b'
    - '#fbfcff'
    - '#b7a597'
    - '#8d8077'
    - '#010101'
  brandStrength: 1
  lightness: 0.239151
  saturation: 0.2558247
  rhythmicContrast: 0.01036679
purpose: []
